#! ruby
require 'test/unit'
require 'helpema'

class TestVersion < Test::Unit::TestCase
  def test_helpema_requires
    loaded = Helpema.requires'
    helpema ~>4.0
    ruby ~>3.0
    json ~>2.0'
    assert_equal ['json'], loaded
  end

  using Helpema::Refinements

  def test_satisfes
    assert_equal false, '1.1'.satisfies?('>1.1', '<1.3')
    assert_equal true, ' 1.2'.satisfies?('>1.1', '<1.3')
    assert_equal false, '1.3'.satisfies?('>1.1', '<1.3')

    assert_equal false, '2.6.9'.satisfies?('~>2.7')
    assert_equal true,  '2.7.0'.satisfies?('~>2.7')
    assert_equal true, ' 2.9.9'.satisfies?('~>2.7')
    assert_equal false, '3.0.0'.satisfies?('~>2.7')
  end

  def test_requires
    loaded = assert_nothing_raised do
      requires 'ruby ~>3.0', 'helpema ~>4.0'
    end
    assert loaded.is_a? Array
    assert loaded.empty?
    error = assert_raises(RuntimeError) do
      requires 'ruby ~>3.0', 'helpema ~>1.0'
    end
    assert_match /helpema.*not ~>1.0/, error.message
    error = assert_raises(RuntimeError) do
      requires 'ruby ~>1.0', 'helpema ~>4.0'
    end
    assert_match /ruby.*not ~>1.0/, error.message
    loaded = requires'
    helpema ~>4.0
    ruby ~>3.0
    set ~>1.0'
    assert_equal ['set'], loaded
  end
end
