#! ruby
require 'test/unit'
require 'helpema'

class TestRubish < Test::Unit::TestCase
  def test_fish
    assert_equal Helpema::Rubish.fish('echo "Hello!"'), "Hello!\n"
  end
  def test_fish_bool
    assert_equal Helpema::Rubish.fish?('true'), true
    assert_equal Helpema::Rubish.fish?('false'), false
  end
  def test_command
    Helpema::Rubish.command :date
    assert_equal Helpema::Rubish.date(d: 'Dec 31, 2020',I: true), "2020-12-31\n"
  end
  def test_shell
    error = nil
    begin
      Helpema::Rubish.shell :ruby, version: 'ruby 1'
    rescue
      error = $!.message
    end
    assert_equal error, '`ruby --version` !~ ruby 1'
    Helpema::Rubish.shell :ruby, version: 'ruby 3', default: 'puts RUBY_VERSION'
    assert_equal Helpema::Rubish.ruby('puts "Hello!"'), "Hello!\n"
    assert_equal Helpema::Rubish.ruby, "3.2.0\n"
  end

  include Helpema
  def test_exception
    Rubish.shell(:fish!, exception: 'Bang!')
    assert_equal "OK\n", Rubish.fish!('echo "OK"')
    error = assert_raises(RuntimeError){Rubish.fish!('false')}
    assert_equal 'Bang!', error.message
  end
end
