#! ruby
require 'test/unit'
require 'helpema'

class TestHelpema < Test::Unit::TestCase
  def test_ssss
    assert_nothing_raised() do
      pwds = Helpema::SSSS.split('MyTopSecretPassphrase', 3, 6)
      assert_equal 6, pwds.length
      secret1 = Helpema::SSSS.combine(pwds[1], pwds[3], pwds[5])
      secret2 = Helpema::SSSS.combine(pwds[0], pwds[2], pwds[4])
      assert_equal 'MyTopSecretPassphrase', secret1
      assert_equal 'MyTopSecretPassphrase', secret2
    end
  end
end
