#! ruby
require 'test/unit'
require 'helpema'
include Helpema

class TestHelpema < Test::Unit::TestCase
  def test_youtubedl
    assert_nothing_raised() do
      YouTubeDL.json(url: 'caca') do |obj|
        assert_equal String, obj.class
        assert_match(/^ERROR:/, obj)
      end
    end
  end
end
