#! ruby
require 'test/unit'
require 'helpema'

class TestHelpema < Test::Unit::TestCase
  def test_youtubedl
    assert_nothing_raised() do
      Helpema::YouTubeDL.json('caca') do |obj|
        assert_equal String, obj.class
        assert_match(/^ERROR:/, obj)
      end
    end

    list = []
    url = 'https://www.youtube.com/watch?v=u4oK3ZSccZI'
    Helpema::YouTubeDL.json(url){|json| list.push json}
    assert_equal 1, list.length # The url was for just one video
    assert_equal "Fortnite Easy Last Ten", list[0]['title']
  end
end
