#! ruby
require 'test/unit'
require 'helpema/zbar'
include HELPEMA

class TestHelpema < Test::Unit::TestCase
  def test_zbar
    assert_nothing_raised() do
      # Just check that it runs, needs "live" testing.
      q = ZBar.cam
      assert_nil q
    end
  end
end
